__version__ = '0.1.4'

from lsdo_soft_csm.core.robotic_fish_static_structural_model import robotic_fish_static_structural_model
from lsdo_soft_csm.core.big_robotic_fish_static_structural_model import big_robotic_fish_static_structural_model
from lsdo_soft_csm.core.robotic_fish_static_structural_model_front_fixed import robotic_fish_static_structural_model_front_fixed
from lsdo_soft_csm.core.cube_static_structural_model import cube_static_structural_model

